name: FORCE_RUN_AUTOWINI

on:
  workflow_dispatch: 

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          # ყურადღება: libasound2 შეიცვალა libasound2t64-ით
          sudo apt-get install -y libgbm-dev wget gnupg libnss3 libatk-bridge2.0-0 libgtk-3-0 libasound2t64 xvfb

      - name: Install Node Packages
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios

      - name: Install Puppeteer Chrome
        run: npx puppeteer browsers install chrome

      - name: Final Launch
        run: xvfb-run --server-args="-screen 0 1920x1080x24" node scraper.js