name: FORCE_RUN_AUTOWINID

on:
  workflow_dispatch: 

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install JS Packages
        run: npm install puppeteer-extra puppeteer-extra-plugin-stealth axios puppeteer

      - name: Install Chrome and All System Dependencies
        # ეს ხაზი თავად მიხვდება, რომ libasound2t64 გჭირდებათ და დააყენებს
        run: npx puppeteer browsers install chrome --install-deps

      - name: Final Launch
        # XVFB სჭირდება ბრაუზერის "დასანახად" ვირტუალურ სივრცეში
        run: xvfb-run --server-args="-screen 0 1920x1080x24" node scraper.js
